# nfs-storage.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/monitoring
    server: 192.168.10.112
  persistentVolumeReclaimPolicy: Retain


