### This script installs the NFS Subdir External Provisioner on a Kubernetes cluster using Helm.
### It creates a StorageClass named "nfs" that uses the NFS Subdir External Provisioner for dynamic provisioning of persistent volumes.
### The script also creates a PersistentVolume and PersistentVolumeClaim for the NFS server.
### The PersistentVolume is set to be used by the NFS Subdir External Provisioner, and the PersistentVolumeClaim is set to use the "nfs" StorageClass.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

