tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo
        persistence:
          enabled: true
          storageClassName: nfs-client
          accessMode: ReadWriteOnce
          size: 10Gi

persistence:
  enabled: true
  storageClassName: nfs-client
  accessMode: ReadWriteOnce
  size: 10Gi

service:
  type: NodePort
  nodePort: 31000
